### ISSUE TITLE
Error when training process is ending

### ISSUE THREAD

**Issue by omerfarukadastec** [smileinnovation/visual-search-yolov5-sagemaker#3]
Hi, I'm trying to use the notebook file of training. Whenever I start to training job, it works well, I can see all the output about training process. I can also see the "best.pt" output, as shown in first image, but after that I get an error as shown in second image. I think it is about docker image, also I am newbie for docker, but I could not find anything to solve it. What should i do? Thanks in advance.

Note: I just added a line to Dockerfile for installing correct version for numpy(1.20.3), because it threw an error about pandas-numpy version compatibility, nothing has changed except this one.

![Screenshot from 2022-09-27 10-39-52](https://user-images.githubusercontent.com/104622368/192464525-40c99cc1-f095-4d31-a8ad-51d7aa291cc3.png)

![Screenshot from 2022-09-27 10-55-05](https://user-images.githubusercontent.com/104622368/192467382-08c0f938-dba8-4459-973f-483905f93700.png)

**Comment by santoshmedisetty** [comment]
@omerfarukadastec, I had the same issue. Change the last line in '/container/train' script to 'cp -r /opt/yolov5/runs/train/$name  /opt/ml/model'. It should work.

**Comment by omerfarukadastec** [comment]
> @omerfarukadastec, I had the same issue. Change the last line in '/container/train' script to 'cp -r /opt/yolov5/runs/train/$name /opt/ml/model'. It should work.

I solved before with your suggestion but i forgot to write the solution. Thanks for the answer and reminding. It worked.
